apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-hello-world-deployment
  labels:
    app: spring-hello-world-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-hello-world-pod
  template:
    metadata:
      labels:
        app: spring-hello-world-pod
    spec:
      containers:
        - name: spring-hello-world-container
          image: joshikeyur/spring-hello-world
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: spring-hello-world-env
                  key: env_name
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: spring-hello-world-secret
                  key: app_password
      #restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: spring-hello-world-service
spec:
  selector:
    app: spring-hello-world-pod
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 9090
      nodePort: 30002