apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-hello-world
  labels:
    app: spring-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-hello-world
  template:
    metadata:
      labels:
        app: spring-hello-world
    spec:
      containers:
        - name: spring-hello-world
          image: joshikeyur/spring-hello-world
          ports:
            - containerPort: 8080
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: spring-hello-world-env
                  key: env_name
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: spring-hello-world-secret
                  key: app_password
---
apiVersion: v1
kind: Service
metadata:
  name: spring-hello-world-service
spec:
  selector:
    app: spring-hello-world
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30002