version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.6

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: ${AWS_ACCOUNT_ID}
          repo: '${MY_APP_PREFIX}'
          tag: '${CIRCLE_SHA1}'
      - aws-ecs/deploy-service-update:
          cluster-name: '${MY_APP_PREFIX}-cluster'
          container-image-name-updates: 'container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}'
          family: '${MY_APP_PREFIX}-service'
          requires:
            - aws-ecr/build-and-push-image
